---
# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# Required
version: 2

formats:
  - htmlzip

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"
  jobs:
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/offeredapis/html/
      - cp -v docs/offeredapis/html/index.html $READTHEDOCS_OUTPUT/html/offeredapis/html/
      - cp -v docs/offeredapis/index.html $READTHEDOCS_OUTPUT/html/offeredapis/
      - cp -v docs/offeredapis/topology-exposure-inventory-openapi.yaml $READTHEDOCS_OUTPUT/html/offeredapis/
      - cp -v docs/offeredapis/topology-exposure-inventory-openapi.json $READTHEDOCS_OUTPUT/html/offeredapis/

python:
  install:
    - requirements: docs/requirements-docs.txt

sphinx:
  configuration: docs/conf.py
